spring:
  application:
    name: wechat-order-discovery-server-ha8762
  output:
    ansi:
      enabled: always
server:
  port: 8762
eureka:
  instance:
    hostname: wechat-order-discovery-server-ha8762
    prefer-ip-address: true
  client:
    service-url:
        defaultZone: http://sherlock:sherlock@wechat-order-discovery-server-ha8761:8761/eureka/
    eureka-server-u-r-l-context: http://wechat-order-discovery-server-ha:8760/
