server:
  port: 8761
eureka:
  instance:
    hostname: wechat-order-discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  output:
    ansi:
      enabled: always


---
#spring:
# profiles: peer1 # 指定profile=peer1
#server:
# port: 8762
#eureka:
# instance:
#  hostname: peer1 # 指定当profile=peer1时， 主机名
# client:
#  serviceUrl:
#   defaultZone: http://discovery:8761/eureka/ # 将⾃⼰注册到peer2这个Eureka上⾯去
#spring:
#  output:
#    ansi:
#      enabled: always
#---
#spring:
# profiles: peer2
#server:
# port: 8762
#eureka:
# instance:
#  hostname: peer2
# client:
#  serviceUrl:
#   defaultZone: http://peer1:8761/eureka/
#spring:
#  output:
#    ansi:
#      enabled: always
